
document.querySelector("#newTaskStartDTButton").addEventListener("click", function () {
    flatpickr("#newTaskStartDT", {
        enableTime: true,
        dateFormat: "Y-m-d H:i",
        allowInput: false,
        clickOpens: false
    }).open();
});

document.querySelector("#newTaskEndDTButton").addEventListener("click", function () {
    flatpickr("#newTaskEndDT", {
        enableTime: true,
        dateFormat: "Y-m-d H:i",
        allowInput: false,
        clickOpens: false
    }).open();
});

document.getElementById('addTaskForm').addEventListener('submit', addTasks);



// Create an array of items for testing
var items = [
    {
        id: 1,
        title: 'Task 1',
    },
    {
        id: 2,
        title: 'Task 2',
    }
];

function showTasks() {
    const cardContent = document.getElementById('card-body');
    cardContent.innerHTML = '';
    cardContent.classList.add('row');

    if (items.length == 0) {
        cardContent.innerHTML = `
            <div class="card-body d-flex align-items-center justify-content-center">
                <p>Currently empty... <br>
                Click <a href="#"> here</a> to find some activities!</p>
            </div>
        `;
        return;
    }

    const taskContainer = document.createElement('div');
    taskContainer.className = 'd-flex align-items-center col mx-5 my-3 p-4';

    taskContainer.id = 'taskContainer';

    const headerDiv = document.createElement('div');
    headerDiv.className = 'headerDiv w-100 justify-content-between';

    const checkboxAndHeaderContainer = document.createElement('div');
    checkboxAndHeaderContainer.className = '';
    checkboxAndHeaderContainer.className = "d-flex align-items-center justify-content-between";
    const checkbox = document.createElement('input');
    checkbox.type = 'checkbox';
    checkboxAndHeaderContainer.appendChild(checkbox);

    const header = document.createElement('h2');
    header.textContent = 'All Tasks';
    header.style.fontFamily = 'Roboto Mono';
    header.style.fontStyle = 'normal';
    header.style.color = '#676767';
    header.classList.add('ms-3')
    checkboxAndHeaderContainer.appendChild(header);

    headerDiv.appendChild(checkboxAndHeaderContainer);

    const dropdown = document.createElement('select');
    const placeholderOption = document.createElement('option');
    placeholderOption.textContent = 'SortBy';
    dropdown.appendChild(placeholderOption);

    headerDiv.appendChild(dropdown);
    taskContainer.appendChild(headerDiv);
    
    const hr = document.createElement('hr');
    hr.className = 'double w-100';
    taskContainer.appendChild(hr);

    // Create another new card
    const dueTaskContainer = document.createElement('div');
    dueTaskContainer.className = 'd-flex align-items-center justify-content-between col mx-5 my-3';
    dueTaskContainer.id = 'dueTaskContainer';

    // Add each item to the card
    items.forEach(function (item) {
        const itemElement = document.createElement('div');
        itemElement.className = 'w-100 d-flex';
        const itemCheckbox = document.createElement('input');
        itemCheckbox.type = 'checkbox';
        itemCheckbox.value = item.id;
        itemCheckbox.className = 'me-3';
        itemElement.appendChild(itemCheckbox);
        
        const itemBox = document.createElement('div');
        itemBox.className = 'rounded bg-light w-100 p-3 mt-3';
        itemBox.textContent = item.title;
        itemBox.addEventListener('click', () => viewDetailedTasks(item));
        itemElement.appendChild(itemBox);
        taskContainer.appendChild(itemElement);
    });

    cardContent.appendChild(taskContainer);
    cardContent.appendChild(dueTaskContainer);
}

// Function to view detailed tasks
function viewDetailedTasks(item) {
    // Code to view detailed tasks goes here
    console.log(item);
}

// Function to add tasks
function addTasks() {
    const form = document.getElementById('addTaskForm');
    const interestedInputs = [];
    interestedInputs.push(...form.querySelectorAll('input[type="text"]'));
    interestedInputs.push(...form.querySelectorAll('input[name="inOrOut"]:checked'));

    const taskObj = {};

    interestedInputs.forEach(input => {
        taskObj[input.name] = input.value;
    });

    // add taskObj to database. For now, simulate by adding to items array.
    // Delete when database is ready, id is generated by the database
    const generatedId = Math.ceil(Math.random() * 10000000);
    taskObj['id'] = generatedId;
    items.push(taskObj);
    showTasks();
}

// Function to edit tasks
function editTasks() {
    // Code to edit tasks goes here
}

// Function to delete tasks
function deleteTasks() {
    // Code to delete tasks goes here
}


// Function to handle all tasks
function allTasks() {
    // Call the function to update the card content
    showTasks();

    // // Call the function to view detailed tasks
    // viewDetailedTasks();

    // // Call the function to add tasks
    // addTasks();

    // // Call the function to edit tasks
    // editTasks();

    // // Call the function to delete tasks
    // deleteTasks();
}

// Call the function to handle all tasks
allTasks();